services:
  postgres-db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=Database123!
    volumes:
      - ./../../postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      sh -c "docker-entrypoint.sh postgres &&
             psql -U postgres -c 'CREATE DATABASE \"demo-db\";'"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadminuser@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Database123!
    ports:
      - "8080:80"
    depends_on:
      - postgres-db